I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cal.rpy", line 557, in script
    show cal neutral happy
Exception: Image 'cal neutral' does not accept attributes 'happy'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cal.rpy", line 557, in script
    show cal neutral happy
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\ast.py", line 1117, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\ast.py", line 1080, in show_imspec
    renpy.config.show(name,
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\calch\Desktop\stuff\renpy-8.0.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'cal neutral' does not accept attributes 'happy'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
DateEboard 1.0
Fri Feb 28 00:21:01 2025
